# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.6
      sudo: false
    - os: osx
      language: generic
      before_install:
        - if [ ! -e $HOME/conda/bin/activate ]; then
          wget --quiet -nc https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
          bash Miniconda3-latest-MacOSX-x86_64.sh -f -b -p $HOME/conda;
          fi
        - source $HOME/conda/bin/activate root

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -r requirements_dev.txt
- python setup.py develop

# Command to run tests, e.g. python setup.py test
script:
- pytest --cov --cov-report=xml --junitxml pytests.xml
# SonarCloud does not understand coverage file with filenames relative to doi2cff so make . sourcedir
- perl -pi -e 's@/doi2cff@@;s@filename="@filename="doi2cff/@' coverage.xml
- sonar-scanner -Dsonar.login=$SONAR_TOKEN -X

addons:
  sonarcloud:
    organization: citation-file-format
