# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.6
      sudo: false
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew upgrade python3
        - /usr/local/opt/python/libexec/bin/pip install virtualenv
        - /usr/local/opt/python/libexec/bin/virtualenv env -p python3
        - source env/bin/activate

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
- tox
# SonarCloud does not understand coverage file with filenames relative to doi2cff so make . sourcedir
- perl -pi -e 's@/doi2cff@@;s@filename="@filename="doi2cff/@' coverage.xml
- sonar-scanner -Dsonar.login=$SONAR_TOKEN -X

addons:
  sonarcloud:
    organization: citation-file-format
